"""
Page 4: Personalized Attraction Recommender.
Interacts with the Phase 4 Hybrid Recommendation Engine (Collaborative Filtering + Content-Based TF-IDF).
Generates ranked attraction recommendations with cold-start fallback for unknown users.
"""

import sys
import re
from pathlib import Path
import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data.preprocessor import build_consolidated_dataset


st.set_page_config(page_title="Personalized Recommender | Tourism Analytics", page_icon="🎯", layout="wide")


@st.cache_resource
def load_recommender():
    rec_path = PROJECT_ROOT / "artifacts" / "recommender.pkl"
    if not rec_path.exists():
        st.error("Recommender artifact not found! Please ensure Phase 4 training has executed.")
        st.stop()
    return joblib.load(rec_path)


@st.cache_data
def get_master_data():
    return build_consolidated_dataset()


def get_attraction_display_location(row: pd.Series) -> str:
    address = str(row.get("AttractionAddress", ""))
    city_name = str(row.get("AttractionCityName", ""))
    att_name = str(row.get("Attraction", ""))

    if city_name in ["Douala", "South Region", "Unknown", "-", ""]:
        known_cities = [
            "Kuta", "Ubud", "Nusa Dua", "Sanur", "Seminyak", "Tabanan", "Tegalalang",
            "Pecatu", "Denpasar", "Badung", "Gianyar", "Bedugul", "Candidasa", "Jimbaran",
            "Malang", "Batu", "Surabaya", "Yogyakarta", "Sleman", "Bantul", "Jakarta",
            "Bandung", "Bogor", "Semarang", "Solo", "Surakarta", "Lombok", "Labuan Bajo"
        ]
        for c in known_cities:
            if re.search(r'\b' + re.escape(c) + r'\b', address, re.IGNORECASE) or re.search(r'\b' + re.escape(c) + r'\b', att_name, re.IGNORECASE):
                return c

        parts = [p.strip() for p in address.split(",") if p.strip()]
        for part in reversed(parts):
            clean_part = re.sub(r'\d+', '', part).replace("Indonesia", "").strip()
            if clean_part and len(clean_part) > 2 and clean_part.lower() not in ["indonesia", "jl", "jalan"]:
                return clean_part

    return city_name


def get_cold_start_diverse_recommendations(hybrid_rec, top_k: int = 5) -> pd.DataFrame:
    pop = hybrid_rec.popular_items.copy()
    selected_rows = []
    country_counts = {}

    for _, row in pop.iterrows():
        cid = row.get("AttractionCountryId", 0)
        if country_counts.get(cid, 0) < 1:
            selected_rows.append(row)
            country_counts[cid] = country_counts.get(cid, 0) + 1
        if len(selected_rows) == top_k:
            break

    if len(selected_rows) < top_k:
        selected_ids = set(r["AttractionId"] for r in selected_rows)
        for _, row in pop.iterrows():
            if row["AttractionId"] not in selected_ids:
                selected_rows.append(row)
            if len(selected_rows) == top_k:
                break

    recs = pd.DataFrame(selected_rows)
    recs["Score"] = recs["Popularity_Score"]
    recs["Recommendation_Type"] = "Popularity Fallback (Cold-Start Diversity)"
    output_cols = [
        "AttractionId", "Attraction", "AttractionType",
        "AttractionCityName", "AttractionCountryId", "AttractionAddress", "Attraction_Avg_Rating",
        "Score", "Recommendation_Type"
    ]
    existing_cols = [c for c in output_cols if c in recs.columns]
    return recs[existing_cols].reset_index(drop=True)


def main():
    # 1. HEADER (Single concise subtitle)
    st.markdown("## 🎯 Personalized Attraction Recommendation Engine")
    st.markdown("Tailored attraction suggestions generated by blending traveler rating patterns and attraction content metadata.")

    rec_bundle = load_recommender()
    hybrid_rec = rec_bundle["hybrid_recommender"]
    eval_metrics = rec_bundle.get("evaluation_metrics", {})
    master_df, _, items_df = get_master_data()

    # 2. HOW RECOMMENDATIONS ARE GENERATED (Immediately below header)
    st.markdown("### 🧠 How Recommendations Are Generated")
    hw_col1, hw_col2, hw_col3 = st.columns(3)

    with hw_col1:
        st.markdown(
            """
            <div style="background: rgba(30, 41, 59, 0.5); border: 1px solid rgba(255, 255, 255, 0.08); border-top: 3px solid #38BDF8; border-radius: 10px; padding: 14px 16px; height: 100%;">
                <div style="font-size: 0.76rem; font-weight: 700; color: #38BDF8; text-transform: uppercase; margin-bottom: 2px;">Step 1</div>
                <div style="font-size: 0.96rem; font-weight: 600; color: #F8FAFC; margin-bottom: 4px;">1. Collaborative Filtering</div>
                <div style="font-size: 0.84rem; color: #94A3B8; line-height: 1.4;">
                    Uses traveler interaction/rating patterns.
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with hw_col2:
        st.markdown(
            """
            <div style="background: rgba(30, 41, 59, 0.5); border: 1px solid rgba(255, 255, 255, 0.08); border-top: 3px solid #818CF8; border-radius: 10px; padding: 14px 16px; height: 100%;">
                <div style="font-size: 0.76rem; font-weight: 700; color: #818CF8; text-transform: uppercase; margin-bottom: 2px;">Step 2</div>
                <div style="font-size: 0.96rem; font-weight: 600; color: #F8FAFC; margin-bottom: 4px;">2. Content-Based Recommendation</div>
                <div style="font-size: 0.84rem; color: #94A3B8; line-height: 1.4;">
                    Uses attraction metadata/content similarity through TF-IDF.
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with hw_col3:
        st.markdown(
            """
            <div style="background: rgba(30, 41, 59, 0.5); border: 1px solid rgba(255, 255, 255, 0.08); border-top: 3px solid #C084FC; border-radius: 10px; padding: 14px 16px; height: 100%;">
                <div style="font-size: 0.76rem; font-weight: 700; color: #C084FC; text-transform: uppercase; margin-bottom: 2px;">Step 3</div>
                <div style="font-size: 0.96rem; font-weight: 600; color: #F8FAFC; margin-bottom: 4px;">3. Hybrid Ranking</div>
                <div style="font-size: 0.84rem; color: #94A3B8; line-height: 1.4;">
                    Combines the available signals into the final ranking.
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # 3. RECOMMENDATION MODEL PERFORMANCE (Immediately AFTER How Recommendations Are Generated)
    if eval_metrics:
        st.markdown("### 📊 Recommendation Model Performance")
        m_col1, m_col2, m_col3 = st.columns(3)
        map_val = eval_metrics.get("MAP@K", 0.5201)
        prec_val = eval_metrics.get("Precision@K", 0.1092)
        rec_val = eval_metrics.get("Recall@K", 0.5460)

        with m_col1:
            st.metric("MAP@5", f"{map_val:.4f}")
        with m_col2:
            st.metric("Precision@5", f"{prec_val:.4f}")
        with m_col3:
            st.metric("Recall@5", f"{rec_val:.4f}")

        st.markdown(
            "<div style='font-size: 0.82rem; color: #94A3B8; margin-top: -6px; margin-bottom: 16px;'>"
            "Offline evaluation on held-out interactions."
            "</div>",
            unsafe_allow_html=True
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # 4. FILTERS + TRAVELER CONTEXT (Two equal-width side-by-side compact cards with aligned height)
    col_left, col_right = st.columns(2)

    with col_left:
        st.markdown("### ⚙️ Recommendation Filters")

        user_mode = st.radio(
            "Traveler History Type:",
            ["Existing Traveler", "New / Unknown Traveler (Cold Start)"],
            index=0,
            horizontal=True
        )

        col_u1, col_u2 = st.columns(2)

        with col_u1:
            if user_mode == "Existing Traveler":
                sample_users = sorted(list(hybrid_rec.user_history.keys()))[:100]
                selected_uid = st.number_input(
                    "User ID:",
                    min_value=1,
                    max_value=999999,
                    value=sample_users[0],
                    step=1
                )
            else:
                selected_uid = None
                st.caption("Cold-start fallback active.")

        with col_u2:
            top_k = st.slider("Recommendations (Top-K):", min_value=3, max_value=15, value=5)

        st.markdown(
            "<div style='font-size: 0.88rem; font-weight: 600; color: #E2E8F0; margin-bottom: 2px;'>"
            "Hybrid Recommendation Balance (α):"
            "</div>",
            unsafe_allow_html=True
        )
        alpha = st.slider(
            "Hybrid Balance Slider",
            min_value=0.0,
            max_value=1.0,
            value=0.5,
            step=0.05,
            label_visibility="collapsed"
        )
        st.markdown(
            f"""
            <div style="text-align: center; font-size: 0.82rem; color: #94A3B8; margin-top: -2px; margin-bottom: 4px;">
                Content-Based &nbsp;←────── <strong style="color: #818CF8;">α = {alpha:.2f}</strong> ──────→ &nbsp; Collaborative
            </div>
            <div style="font-size: 0.78rem; color: #94A3B8; line-height: 1.3; margin-bottom: 12px;">
                Controls the balance between content similarity and collaborative traveler preferences.
            </div>
            """,
            unsafe_allow_html=True
        )

        get_recs_btn = st.button("✨ Generate Recommendations", type="primary", width="stretch")

    with col_right:
        st.markdown("### 👤 Traveler Context")

        if user_mode == "Existing Traveler":
            st.markdown(
                f"""
                <div style="background: rgba(30, 41, 59, 0.6); border: 1px solid rgba(56, 189, 248, 0.3); border-radius: 12px; padding: 18px 20px; display: flex; flex-direction: column; justify-content: space-around; min-height: 270px; box-sizing: border-box;">
                    <div>
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">Traveler Type</span>
                        <strong style="font-size: 1.0rem; color: #F8FAFC;">Existing Traveler</strong>
                    </div>
                    <div style="border-top: 1px solid rgba(255,255,255,0.08); padding-top: 10px;">
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">User ID</span>
                        <strong style="font-size: 1.1rem; color: #38BDF8;">#{selected_uid}</strong>
                    </div>
                    <div style="border-top: 1px solid rgba(255,255,255,0.08); padding-top: 10px;">
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">Recommendation Mode</span>
                        <strong style="font-size: 1.0rem; color: #818CF8;">Personalized Hybrid Recommendation</strong>
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
        else:
            st.markdown(
                """
                <div style="background: rgba(30, 41, 59, 0.6); border: 1px solid rgba(251, 146, 60, 0.3); border-radius: 12px; padding: 18px 20px; display: flex; flex-direction: column; justify-content: space-around; min-height: 270px; box-sizing: border-box;">
                    <div>
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">Traveler Type</span>
                        <strong style="font-size: 1.0rem; color: #F8FAFC;">New / Unknown Traveler</strong>
                    </div>
                    <div style="border-top: 1px solid rgba(255,255,255,0.08); padding-top: 10px;">
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">User ID</span>
                        <strong style="font-size: 1.1rem; color: #64748B;">—</strong>
                    </div>
                    <div style="border-top: 1px solid rgba(255,255,255,0.08); padding-top: 10px;">
                        <span style="font-size: 0.75rem; color: #94A3B8; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 2px;">Recommendation Mode</span>
                        <strong style="font-size: 1.0rem; color: #FB923C;">Cold-Start Popularity + Diversity Fallback</strong>
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )

    st.markdown("---")

    # Recommendation Generation logic
    if user_mode == "Existing Traveler":
        recs_df = hybrid_rec.recommend(user_id=selected_uid, top_k=top_k, alpha=alpha)
    else:
        recs_df = get_cold_start_diverse_recommendations(hybrid_rec, top_k=top_k)

    rec_type = recs_df["Recommendation_Type"].iloc[0] if not recs_df.empty else ""
    is_cold_start = "Cold" in rec_type or user_mode != "Existing Traveler"

    # 5. COLD-START INFORMATION (For New / Unknown Traveler only)
    if is_cold_start:
        st.markdown(
            """
            <div style="background: rgba(251, 146, 60, 0.1); border: 1px solid rgba(251, 146, 60, 0.3); border-radius: 10px; padding: 12px 18px; margin-bottom: 16px;">
                <div style="font-size: 0.95rem; font-weight: 700; color: #FB923C; margin-bottom: 2px;">🆕 Cold-Start Mode</div>
                <div style="font-size: 0.85rem; color: #CBD5E1;">
                    No previous traveler history is available. Recommendations use popularity with geographic diversity to provide a broader starting set.
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )
        heading_title = f"🏆 Top {len(recs_df)} Diverse Popular Attraction Recommendations"
        sub_explanation = "Ranked using popularity signals with geographic diversity for cold-start discovery."
    else:
        heading_title = f"🏆 Top {len(recs_df)} Personalized Attraction Recommendations"
        sub_explanation = "Ranked using the hybrid recommendation model combining traveler behavior and attraction content."

    # 6. RECOMMENDATION RESULTS (Main visual focus)
    st.markdown(f"### {heading_title}")
    st.markdown(
        f"<div style='font-size: 0.86rem; color: #94A3B8; margin-top: -6px; margin-bottom: 16px;'>{sub_explanation}</div>",
        unsafe_allow_html=True
    )

    if recs_df.empty:
        st.info("No recommendations found matching current criteria.")
    else:
        for i in range(0, len(recs_df), 2):
            cols = st.columns(2)
            for j in range(2):
                idx = i + j
                if idx < len(recs_df):
                    row = recs_df.iloc[idx]
                    raw_score = row["Score"]

                    if is_cold_start:
                        score_label = "Popularity Score"
                        score_val_str = f"{raw_score:.2f}"
                    else:
                        score_label = "Hybrid Recommendation Score"
                        score_val_str = f"{raw_score * 100.0:.1f}%"

                    location_display = get_attraction_display_location(row)

                    with cols[j]:
                        st.markdown(
                            f"""
                            <div style="background: rgba(30, 41, 59, 0.6); border: 1px solid rgba(255, 255, 255, 0.08); border-left: 4px solid #38BDF8; border-radius: 12px; padding: 18px 20px; margin-bottom: 16px; display: flex; flex-direction: column; justify-content: space-between; min-height: 190px;">
                                <div>
                                    <div style="display: flex; justify-content: space-between; align-items: flex-start; gap: 10px; margin-bottom: 10px;">
                                        <span style="font-size: 1.15rem; font-weight: 700; color: #F8FAFC; line-height: 1.3;">
                                            #{idx + 1}. {row['Attraction']}
                                        </span>
                                        <span style="background: rgba(56, 189, 248, 0.15); color: #38BDF8; border: 1px solid rgba(56, 189, 248, 0.4); padding: 3px 10px; border-radius: 14px; font-weight: 600; font-size: 0.82rem; white-space: nowrap;">
                                            {score_label}: {score_val_str}
                                        </span>
                                    </div>
                                    <div style="color: #94A3B8; font-size: 0.88rem; line-height: 1.6; margin-bottom: 10px;">
                                        <div>⭐ Average Rating: <strong style="color: #FACC15;">{row['Attraction_Avg_Rating']:.2f} / 5.0</strong></div>
                                        <div>📍 Location: <strong style="color: #E2E8F0;">{location_display}</strong></div>
                                        <div>🏷️ Category: <strong style="color: #CBD5E1;">{row['AttractionType']}</strong></div>
                                    </div>
                                    <div style="color: #64748B; font-size: 0.82rem; border-top: 1px solid rgba(255,255,255,0.05); padding-top: 8px; margin-top: 6px;">
                                        <strong>Address:</strong> {row['AttractionAddress']}
                                    </div>
                                </div>
                            </div>
                            """,
                            unsafe_allow_html=True
                        )


if __name__ == "__main__":
    main()
